require 'open-uri'
require 'mechanize'
require 'nokogiri'
require 'json'
require 'terminal-table'
require 'gruff'

require_relative 'lib/nba_stats_cli/cli'
require_relative 'lib/nba_stats_cli/current_scores'
require_relative 'lib/nba_stats_cli/player_scraper'
require_relative 'lib/nba_stats_cli/team_scraper'
