source 'https://rubygems.org'

gem 'sinatra', '1.4.0'
gem 'activerecord', '4.2.4', require: 'active_record'
gem 'sqlite3', '1.3.11'
gem 'bcrypt', '3.1.10'
gem 'json'
gem 'terminal-table'
gem 'thor'
gem 'nokogiri'
gem 'mechanize'
